spring:
  application:
    name: reservation
  datasource:
    url: jdbc:h2:mem:testdb
    driverClassName: org.h2.Driver
    username: root
    password: 23610703
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
  h2:
    console:
      enabled: true
      path: /h2-console
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest


server:
  port: 8083
  servlet:
    context-path: /reservation
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/



# Path: Projet_base_de_donnees/serveur-registre/src/main/resources/application.yml