spring:
    application:
        name: bienImmo # le nom de notre application

    datasource:
        url: jdbc:h2:mem:bienImmoDb
        driverClassName: org.h2.Driver
        username: root
        password: password
    jpa:
        database-platform: org.hibernate.dialect.H2Dialect
    h2:
        console:
            enabled: true
            path: /h2-console

    rabbitmq:
        host: localhost
        port: 5672
        username: guest
        password: guest

server:
    port: 8081
    servlet:
        context-path: /bienImmo # le context path de notre application

eureka:
    client:
        serviceUrl:
            defaultZone: http://localhost:8761/eureka #le lien vers le serveur eureka
    instance:
        instance-id: ${spring.application.name}:${spring.application.instance_id:${random.value}}